/**
 * Trabalho realizado para a disciplina de Processamento Digital de Imagens
 * da PUC Minas no 1° Semestre de 2016 pela aluna Ana Coimbra
 * 
 * 
 * Observacoes: 
 * 1 - Ideal utilizar imagens com resolucao 256x256. Existem algumas 
 * na pasta do projeto para utilizacao
 * 2 - Atualmente nao esta implementado tratamento de erros e ainda existem 
 * alguns bugs na vizualizacao das imagens, principalmente as de saida. Entao,
 * se for o caso, basta abrir a imagem output.jpg dentro da pasta do projeto.
 */
package pdi.puc;

import java.awt.image.BufferedImage;
import java.io.Console;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Ana Coimbra
 */
public class PrimeiroTrabalho extends javax.swing.JFrame {

    /**
     * Creates new form PrimeiroTrabalho
     */
    public PrimeiroTrabalho() throws IOException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOperacoes = new javax.swing.JButton();
        btnFiltros = new javax.swing.JButton();
        btnRuidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Processamento Digital de Imagens");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOperacoes.setText("Operações");
        btnOperacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperacoesActionPerformed(evt);
            }
        });
        jPanel1.add(btnOperacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 207, 96));

        btnFiltros.setText("Filtros");
        btnFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrosActionPerformed(evt);
            }
        });
        jPanel1.add(btnFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, 207, 96));

        btnRuidos.setText("Ruído");
        btnRuidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRuidosActionPerformed(evt);
            }
        });
        jPanel1.add(btnRuidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 207, 96));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrosActionPerformed
        /**
         * Questao 2 : filtragem espacial - filtros passa-baixa
         */
        Questao2 q2 = new Questao2();
        q2.setVisible(true);
    }//GEN-LAST:event_btnFiltrosActionPerformed

    private void btnOperacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacoesActionPerformed
        /**
         * Questao 1 : operacoes com imagens
         */
        Questao1 q1 = new Questao1();
        q1.setVisible(true);
    }//GEN-LAST:event_btnOperacoesActionPerformed

    private void btnRuidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRuidosActionPerformed
        /**
         * Questao 3 : testes com desvio padrao
         */
        Questao3 q3 = new Questao3();
        q3.setVisible(true);
    }//GEN-LAST:event_btnRuidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimeiroTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimeiroTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimeiroTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimeiroTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PrimeiroTrabalho().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(PrimeiroTrabalho.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltros;
    private javax.swing.JButton btnOperacoes;
    private javax.swing.JButton btnRuidos;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
